# Generated by Django 2.2.6 on 2022-11-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221117_2230'),
        ('posts', '0007_comment'),
    ]

    operations = [
    ]
